#!/usr/bin/env python3
"""Validate certificate information from iTop against remote machines.

This script:
- Reads the CSV file generated by export_cert_info.py.
- For each row (machine), uses SSH to connect to the machine by IP.
- Runs a configurable command on the remote host to print certificate info.
- Compares the remote certificate info with the values from iTop.
- Writes a CSV with columns: name,ip,cert_is_valid where cert_is_valid is one of:
    - "yes"          -> remote cert info matches iTop values
    - "no"           -> remote cert info is reachable but does NOT match iTop
    - "unreachable"  -> SSH failed or required a password

ASSUMPTIONS / TO ADAPT:
- SSH authentication is passwordless for the given user (e.g. ansibleadmin).
- The remote command prints a single line with three comma-separated fields:
    certrenewaldate,currentcertstartdate,currentcertenddate
  in the same formats as stored in iTop.
  You can change REMOTE_CERT_COMMAND and/or adjust parse_remote_cert_info()
  if your environment is different.
"""

import argparse
import csv
import logging
import subprocess
from datetime import datetime
from typing import Dict, Optional, Tuple

logger = logging.getLogger(__name__)

# Default remote command for RHEL/Linux hosts.
#
# It will:
# - Search /etc/pki/tls/certs for the first non-CA cert file with extension
#   .crt, .cer, or .cert (case-insensitive), excluding filenames that contain
#   "ca" (to avoid CA certs).
# - Use openssl x509 to print notBefore and notAfter dates.
#
# The Python side (parse_remote_cert_info) will interpret this output and map:
#   notBefore -> currentcertstartdate
#   notAfter  -> certrenewaldate and currentcertenddate
REMOTE_CERT_COMMAND = (
    "sh -c '"
    "cert=$(find /etc/pki/tls/certs -maxdepth 1 -type f "
    "\\( -iname \"*.crt\" -o -iname \"*.cer\" -o -iname \"*.cert\" \\) "
    "! -iname \"*ca*\" -print -quit); "
    "[ -z \"$cert\" ] && exit 1; "
    "openssl x509 -in \"$cert\" -noout -startdate -enddate'"
)


def run_ssh_command(host: str, user: str, command: str, timeout: int = 15) -> Tuple[int, str, str]:
    """Run a command on a remote host via ssh.

    Returns (returncode, stdout, stderr).
    If the host is unreachable or password is required, returncode will be non-zero.
    """
    ssh_cmd = [
        "ssh",
        "-o",
        "BatchMode=yes",  # do not prompt for password
        "-o",
        f"ConnectTimeout={timeout}",
        f"{user}@{host}",
        command,
    ]

    try:
        proc = subprocess.run(
            ssh_cmd,
            capture_output=True,
            text=True,
            timeout=timeout + 5,
        )
        return proc.returncode, proc.stdout.strip(), proc.stderr.strip()
    except Exception as e:
        logger.error("SSH to %s failed: %s", host, e)
        return 1, "", str(e)


def parse_remote_cert_info(output: str) -> Dict[str, str]:
    """Parse remote openssl output into a dict of cert fields.

    Expected format from REMOTE_CERT_COMMAND (openssl x509 -noout -startdate -enddate):
        notBefore=...
        notAfter=...

    Returns a dict with keys 'certrenewaldate', 'currentcertstartdate', 'currentcertenddate'.
    If parsing fails, returns an empty dict.
    """
    if not output:
        return {}

    not_before: Optional[str] = None
    not_after: Optional[str] = None

    for line in output.splitlines():
        line = line.strip()
        if line.startswith("notBefore="):
            not_before = line.split("=", 1)[1].strip()
        elif line.startswith("notAfter="):
            not_after = line.split("=", 1)[1].strip()

    if not_after is None:
        logger.warning("Unexpected remote cert format (no notAfter): %r", output)
        return {}

    # If notBefore is missing, we still keep going and just duplicate notAfter
    if not_before is None:
        not_before = not_after

    return {
        "certrenewaldate": not_after,
        "currentcertstartdate": not_before,
        "currentcertenddate": not_after,
    }


def _parse_date_flex(value: str) -> Optional[datetime]:
    """Try to parse a date string in several common formats.

    Returns a datetime on success or None on failure.
    """
    if not value:
        return None

    value = value.strip()
    # Common iTop-like and generic datetime formats
    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%dT%H:%M:%SZ",
        # OpenSSL-style: "Jan  1 00:00:00 2025 GMT"
        "%b %d %H:%M:%S %Y %Z",
        "%b %d %H:%M:%S %Y",
    ]

    for fmt in formats:
        try:
            return datetime.strptime(value, fmt)
        except Exception:
            continue

    return None


def compare_cert_info(itop_row: Dict[str, str], remote_info: Dict[str, str]) -> str:
    """Compare iTop cert info row with remote cert info.

    Returns one of:
      - "yes" if all three fields match exactly (string comparison).
      - "no"  if any field differs or remote_info is incomplete.
    """
    required_keys = ["certrenewaldate", "currentcertstartdate", "currentcertenddate"]

    # If we have no remote info or missing fields, treat as mismatch.
    if not remote_info or any(k not in remote_info or remote_info[k] == "" for k in required_keys):
        return "no"

    for key in required_keys:
        itop_raw = (itop_row.get(key) or "").strip()
        remote_raw = (remote_info.get(key) or "").strip()

        # First try flexible date parsing and compare by date (ignore time if needed).
        itop_dt = _parse_date_flex(itop_raw)
        remote_dt = _parse_date_flex(remote_raw)

        if itop_dt and remote_dt:
            if itop_dt.date() != remote_dt.date():
                return "no"
        else:
            # Fallback to strict string comparison if parsing fails.
            if itop_raw != remote_raw:
                return "no"

    return "yes"


def process_csv(input_csv: str, output_csv: str, ssh_user: str) -> None:
    """Read export_cert_info CSV, SSH to each host, compare cert info, write results CSV."""
    with open(input_csv, newline="", encoding="utf-8") as f_in, open(
        output_csv, "w", newline="", encoding="utf-8"
    ) as f_out:
        reader = csv.DictReader(f_in)
        fieldnames = ["name", "ip", "cert_is_valid"]
        writer = csv.DictWriter(f_out, fieldnames=fieldnames)
        writer.writeheader()

        for row in reader:
            name = row.get("Name") or row.get("name") or ""
            ip = row.get("IP") or row.get("ip") or ""

            if not ip:
                logger.warning("No IP for row %r; marking as unreachable", name)
                writer.writerow({"name": name, "ip": ip, "cert_is_valid": "unreachable"})
                continue

            # Skip rows that clearly have no cert info in iTop (all three fields empty).
            if not any(
                (row.get(k) or "").strip()
                for k in ("certrenewaldate", "currentcertstartdate", "currentcertenddate")
            ):
                logger.info("No cert info in iTop for %s (%s); marking as no", name, ip)
                writer.writerow({"name": name, "ip": ip, "cert_is_valid": "no"})
                continue

            rc, stdout, stderr = run_ssh_command(ip, ssh_user, REMOTE_CERT_COMMAND)

            if rc != 0:
                # SSH failed or password prompt / permission denied.
                logger.warning(
                    "SSH to %s (%s) failed (rc=%s): %s", name, ip, rc, stderr or stdout
                )
                writer.writerow({"name": name, "ip": ip, "cert_is_valid": "unreachable"})
                continue

            remote_info = parse_remote_cert_info(stdout)
            status = compare_cert_info(row, remote_info)
            writer.writerow({"name": name, "ip": ip, "cert_is_valid": status})


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate certificate info from iTop against remote machines via SSH",
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to input CSV generated by export_cert_info.py",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to output CSV with columns: name,ip,cert_is_valid",
    )
    parser.add_argument(
        "--ssh-user",
        default="ansibleadmin",
        help="SSH username to connect to target machines (default: ansibleadmin)",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging level (default: INFO)",
    )

    args = parser.parse_args()
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s %(levelname)s %(message)s",
    )

    logger.info(
        "Starting cert validation: input=%s, output=%s, ssh_user=%s",
        args.input,
        args.output,
        args.ssh_user,
    )

    process_csv(args.input, args.output, args.ssh_user)
    logger.info("Done. Results written to %s", args.output)


if __name__ == "__main__":
    main()
